- hosts: front
  remote_user: ansible
  become: yes
  tasks:
  - name: コンテントの配置
    copy: src=../content/ dest=/var/www/html/enemy-finder/
  - name: iniの配置(vault)
    copy: src=../ini/ef_value.ini dest=/var/www/ini/ef_value.ini
