- hosts: front
  remote_user: ansible
  vars:
  tasks:
  - name: コンテントの配置
    copy: src=../content/ dest=/home/ansible/test/
  - name: iniの配置
    copy: src=../ini/ef_value.ini dest=/home/ansible/test2/
